// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Us1g8FJ_qH7rfjVgJVAP_ddKZtIVr34',
    appId: '1:1047074779085:web:35f437999b3df93b0a1e84',
    messagingSenderId: '1047074779085',
    projectId: 'vroom-squad',
    authDomain: 'vroom-squad.firebaseapp.com',
    storageBucket: 'vroom-squad.firebasestorage.app',
    measurementId: 'G-QNHP83N3XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7n-rvW1PwxME8tuqav747DFuqUZaDrj0',
    appId: '1:1047074779085:android:191f87400e6683620a1e84',
    messagingSenderId: '1047074779085',
    projectId: 'vroom-squad',
    storageBucket: 'vroom-squad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg8YVLnYpi6fJM0k-wBjFLNqLK2U7f5KE',
    appId: '1:1047074779085:ios:1c53d17f055f8db70a1e84',
    messagingSenderId: '1047074779085',
    projectId: 'vroom-squad',
    storageBucket: 'vroom-squad.firebasestorage.app',
    iosBundleId: 'com.example.carpoolingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg8YVLnYpi6fJM0k-wBjFLNqLK2U7f5KE',
    appId: '1:1047074779085:ios:1c53d17f055f8db70a1e84',
    messagingSenderId: '1047074779085',
    projectId: 'vroom-squad',
    storageBucket: 'vroom-squad.firebasestorage.app',
    iosBundleId: 'com.example.carpoolingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5Us1g8FJ_qH7rfjVgJVAP_ddKZtIVr34',
    appId: '1:1047074779085:web:1ebef6900f0da7780a1e84',
    messagingSenderId: '1047074779085',
    projectId: 'vroom-squad',
    authDomain: 'vroom-squad.firebaseapp.com',
    storageBucket: 'vroom-squad.firebasestorage.app',
    measurementId: 'G-SETXBCH5J9',
  );
}
